# Generated by Django 5.0.2 on 2024-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='用户名称')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户手机号码')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码(hash)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='头像')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个性签名')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否有效')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
