# Generated by Django 5.0.2 on 2024-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desiderii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=2048, verbose_name='用户密码(hash)'),
        ),
    ]
