# Generated by Django 5.0.2 on 2024-03-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desiderii', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
