# Generated by Django 5.0.2 on 2024-03-10 12:40

import desiderii.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desiderii', '0003_rename_uid_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='标签id')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='板块id')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'db_table': 'topic',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=desiderii.models.avatar_name, verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='动态id')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除 0-未删除 1-已删除')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者id')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desiderii.topic', verbose_name='所属板块id')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desiderii.article', verbose_name='所属动态id')),
                ('ccid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desiderii.comment', verbose_name='父评论id')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desiderii.article', verbose_name='动态id')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desiderii.tag', verbose_name='tag id')),
            ],
            options={
                'verbose_name': '动态标签关联',
                'verbose_name_plural': '动态标签关联',
                'db_table': 'article_tag',
            },
        ),
    ]
