# Generated by Django 5.0.2 on 2024-03-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desiderii', '0004_tag_topic_alter_user_avatar_article_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
