# Generated by Django 5.0.2 on 2024-03-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desiderii', '0005_alter_article_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desiderii.topic', verbose_name='所属板块id'),
        ),
    ]
